---
- hosts: localhost
  connection: local
  become: yes
  roles:
    - role: system
      tags: system
    - role: firewall
      tags: firewall
    - role: usb
      tags: usb
    - role: nginx
      tags: nginx
    - role: caddy
      tags: caddy
    - role: syncthing
      tags: syncthing
    - role: geerlingguy.pip
      tags: pip
    - role: geerlingguy.docker_arm
      tags: docker
