- name: Install caddy
  apt:
    name: "caddy"
    state: present
    update_cache: true
- name: allow caddy
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
- name: allow caddy 443
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
- name: reload ufw
  community.general.ufw:
    state: reloaded 
- name: copy index.html
  copy:
    dest: /var/www/html
    src: index.html
    owner: caddy
    group: caddy
    mode: 0777
- name: Start caddy
  service:
    name: caddy
    state: started
    enabled: yes