- name: enable ufw
  community.general.ufw:
    state: enabled
- name: allow ufw all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
- name: allow ufw all access to tcp port 443
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
- name: allow ufw all access to tcp port 21
  community.general.ufw:
    rule: allow
    port: '21'
    proto: tcp
- name: deny ufw all access to tcp port 6379
  community.general.ufw:
    rule: deny
    port: '6379'
    proto: tcp
- name: deny ufw all access to udp port 6379
  community.general.ufw:
    rule: deny
    port: '6379'
    proto: udp
- name: allow ufw all access to tcp port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
- name: allow ufw all access to tcp port 8384
  community.general.ufw:
    rule: allow
    port: '8384'
    proto: tcp
- name: allow ssh
  become: true
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp
- name: reload ufw
  community.general.ufw:
    state: reloaded
- name: enable ufw
  community.general.ufw:
    state: disabled